version: '3'

services:
  trybewallet:
    container_name: pokemon-react-docker
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true    