export const startMap = [
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'WATER', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'WATER', 'GRASS', 'GRASS', 'ROCk', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
    ['GRASS', 'ROCK', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'SAND', 'WATER', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'SAND', 'WATER', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'SAND', 'WOOD',  'SAND', 'GRASS', 'GRASS', 'GRASS', 'ROCk', 'GRASS', 'GRASS'],
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'WATER', 'SAND', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],  
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'WATER', 'SAND', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'WATER', 'SAND', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
    ['GRASS', 'GRASS', 'ROCk', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'WATER', 'GRASS', 'ROCk', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
    ['GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'WATER', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS', 'GRASS'],
  ];